version: '3.8'

services:
  app:
    image: gyehyunbak/payper-server:${IMAGE_TAG}
    ports:
      - "8080"
    env_file:
      - .env
    networks:
      - payper-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - payper-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - payper-network

networks:
  payper-network:
    driver: bridge