services:
  app:
    container_name: app
    image: gyehyunbak/payper-server:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/secrets/firebase-service-account.json:/etc/secrets/firebase-service-account.json:ro
    networks:
      - payper-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    restart: always
    networks:
      - payper-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - payper-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - payper-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"   # 초기 admin 비밀번호 설정
    depends_on:
      - prometheus
    networks:
      - payper-network
    restart: unless-stopped

networks:
  payper-network:
    driver: bridge