services:
  app:
    container_name: app
    image: gyehyunbak/payper-server:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/secrets/firebase-service-account.json:/etc/secrets/firebase-service-account.json:ro
      - /home/ubuntu/payper-app/logs:/logs
    networks:
      - payper-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    restart: always
    networks:
      - payper-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - payper-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.1
    container_name: filebeat
    user: root  # 로그 권한 문제 예방용
    volumes:
      - /home/ubuntu/payper-app/logs:/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - payper-network
    depends_on:
      - app

networks:
  payper-network:
    driver: bridge