jdbc.driver = com.mysql.cj.jdbc.Driver
jdbc.url = jdbc:mysql://localhost:3306/payper
jdbc.username = root
jdbc.password = it2116732

kakao.api.key = aca0b6bad9587b8d156c8ee39bda1ce7
kakao.api.url = https://dapi.kakao.com/v2/local/search/keyword.json
