-Dspring.profiles.active=db, kakao, codef, secret

# file location
# src/main/resources

# !!DO NOT TOUCH!! -> WILL IMPORT VALUES FROM .env
# CODEF
demo.client.id=${DEMO_CLIENT_ID}
demo.client.secret=${DEMO_CLIENT_SECRET}
public.key=${PUBLIC_KEY}

# JDBC (Database)
jdbc.driver=${JDBC_DRIVER}
jdbc.url=${JDBC_URL}
jdbc.username=${JDBC_USERNAME}
jdbc.password=${JDBC_PASSWORD}

# OpenAI
openai.api.key=${OPENAI_API_KEY}
openai.api.url=${OPENAI_API_URL}

# Kakao
kakao.client.id=${KAKAO_CLIENT_ID}
kakao.client.secret=${KAKAO_CLIENT_SECRET}
kakao.redirect.uri=${KAKAO_REDIRECT_URI}
kakao.token.url=${KAKAO_TOKEN_URL}
kakao.user.info.url=${KAKAO_USER_INFO_URL}
kakao.map.key=${KAKAO_MAP_KEY}
kakao.map.url=${KAKAO_MAP_URL}

# Token
token.secret.key=${TOKEN_SECRET_KEY}

# Prometheus
management.endpoints.web.exposure.include=prometheus
management.prometheus.metrics.export.enabled=true

# Fcm
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH}