-Dspring.profiles.active=db, kakao

############ application-db.properties guide ############
#jdbc.driver = com.mysql.cj.jdbc.Driver
#jdbc.url = jdbc:mysql://localhost:3306/{schema-name}
#jdbc.username={username}
#jdbc.password={password}
############################################################

############ application-kakao.properties guide ############
#kakao.api.key={kakao-api-key}
#kakao.api.url={kakao-api-url}
############################################################
